# This is a basic workflow to help you get started with Actions

name: Review Checklist
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: | 
            checklist shouold go here
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
