name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Secrets
      run: 
        cat <<EOF > apikey.properties
        MOVIE_DB_KEY="some-key"
        EOF
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
