
name: Comment

on:
  pull_request:


jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Comment on a pull request
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            checklist should go here
            and here
          repo-token: ${{ secrets.GITHUB_TOKEN }}